### ISSUE TITLE
Add footnote to pages

### ISSUE THREAD

**Issue by BenjaminEchelmeier** [terminal-labs/lektor-theme-terminal#7]
Can we add a footnote field to the page model as an option to throw in a final note or paragraph, particularly on non text-centric pages? Such as https://github.com/terminal-labs/tl_web/issues/39

**Comment by BenjaminEchelmeier** [comment]
This proves to be unneeded currently.
> particularly on non text-centric pages
The best solution in such cases may be to use the body in the template, considering this is likely unused.

There is potential for a need like this to come about, at which point a similar issue might be opened.

**Comment by toonarmycaptain** [comment]
> This proves to be unneeded currently.

I believe it was desired for the pyscript blog, right?

**Comment by BenjaminEchelmeier** [comment]
> > This proves to be unneeded currently.
> 
> I believe it was desired for the pyscript blog, right?

I don't think so. This was designed to put a footer at the base of the "Our Teams" page (where we literally could not add text). For the pyscript blog we just added a graphic to imply a footnote.
